### ISSUE TITLE
mac-autocomplete dropdown placement issue

### ISSUE THREAD

**Issue by AndreasGassmann** [angular-macgyver/MacGyver#11]
Hi,

we recently implement mac-autocomplete into our website. We noticed that every time you enter a new word, the dropdown box appears in the top-left corner for a split-second before it moves to the correct position.

If the autocomplete input field is located further down the page (you have to scroll down), the flickering doesn't occur, probably because it's always positioned in the top left of the page.

We created a plunker to demonstrate the issue:
http://plnkr.co/edit/UYhfMJvJqCNknXvsVmx4

Thanks in advance for your help

**Comment by adrianlee44** [comment]
Hi @AndreasGassmann, thanks for reporting this. Will look into it.

**Comment by CaptainLexington** [comment]
This is also happening to me. It happens even when no other stylesheet is loaded into the app.

**Comment by AndreasGassmann** [comment]
@CaptainLexington I also noticed the second issue you mention (it even happens on the plunker I posted), but surprisingly the "offset issue" doesn't occur on both websites I tested it on. I couldn't figure out why, so I didn't include it in my initial post.

**Comment by adrianlee44** [comment]
@AndreasGassmann, I see the offset issue and will address both issue in the bug fix.

**Comment by adrianlee44** [comment]
`v0.6.1` release should fix the problem. Please let me know if you still see it. Thanks!
