### ISSUE TITLE
Please add demos

### ISSUE THREAD

**Issue by slavafomin** [angular-macgyver/MacGyver#12]
Hello!

Thank you for your library.

However, could you please add some demos?

**Comment by adrianlee44** [comment]
Hi @slavafomin, are there specific demos you want to see first?

**Comment by slavafomin** [comment]
I was looking for a drop-down component with (suggest|typeahead|filter) functionality.

**Comment by v0d1ch** [comment]
Also I think it would be beneficial to add example of adding callbacks. I had to look at the source to figure it out.

**Comment by adrianlee44** [comment]
@v0d1ch, thanks for the interest!

Unfortunately I'm no longer actively maintaining this project and won't update MacGyver to support newer versions of Angular. Angular has a great community and I'm sure there are better alternative solutions.
