### ISSUE TITLE
clicking the a element reloads page (ngRoute),  instead of pointing to anchor.

### ISSUE THREAD

**Issue by morfin** [angular-macgyver/MacGyver#14]
When clicking on any link. AngularJS intercepts and routes me to a completely different page (in my case, a 404-page as there are no routes matching the links.)

I would like to know if this library takes cares of that, or what do you suggest to stop the routing event ?

Thanks.

**Comment by adrianlee44** [comment]
Maybe I ask which directive you are using?

**Comment by morfin** [comment]
mac-scroll-spy-target
mac-scroll-spy-anchor

**Comment by adrianlee44** [comment]
`mac-scroll-spy-target` and `mac-scroll-spy-anchor` shouldn't affect anchor behavior. The two directives only monitor the top offset of each anchor and highlight the target when user scroll into view.

Can you post a code sample to places like plunkr? Thanks.

**Comment by morfin** [comment]
Let me clarify that everything works good. My question is if some of your directives handle the ui-route behavior suppression, that is, rather than letting the router to redirect after clicking URL, the link should point to the anchor. So question is, should I workaround that myself?

**Comment by adrianlee44** [comment]
None of the directives prevent default from happening so you will have to add the suppression yourself.

**Comment by adrianlee44** [comment]
Closing this issue. Please reopen if more help is needed.
