### ISSUE TITLE
grunt wiredep includes both source and compile version

### ISSUE THREAD

**Issue by morfin** [angular-macgyver/MacGyver#17]
Why both versions are defined in .bower.json ?

  "main": [
    "lib/macgyver-core.js",
    "lib/macgyver-filters.js",
    "lib/macgyver-string-filter.js",
    "lib/macgyver.css",
 **"lib/macgyver.js",**
**"lib/macgyver.min.js"**
  ],

This causes grunt wiredep to include both versions.

Just curious,

**Comment by adrianlee44** [comment]
MacGyver started as a Coffeescript project and it's still currently in. Most of the coffeescript files are in the `src` folder. When building a new release, these `.coffee` files will be compiled into `lib/macgyver.js` and `lib/macgyver.min.js`.

When the project started to use Bower around 2 years ago, both files are included to specify all available files for this package. However, it seems like the way `main` is used has changed and should probably be updated.

Will be creating a separate issue to track this.

**Comment by morfin** [comment]
Wonderful, I'll stay in tune.

**Comment by adrianlee44** [comment]
Closing this issue and will be tracking with #18.
