### ISSUE TITLE
mac-modal-data doesn't pass data

### ISSUE THREAD

**Issue by DavidValin** [angular-macgyver/MacGyver#20]
Im using mac-modal like so:

1.
`<i class="fa fa-ellipsis-h" mac-modal="item-control" mac-modal-data="item">&nbsp;</i>`

2.
`<mac-modal id="item-control" mac-modal-keyboard ng-controller="TimeLineCtrl" mac-modal-open="fetchTimeLine(item)">
  <div class="mac-modal-content">
    <label>
      Finish date:
      <input type="text" name="" value="" id="">
    </label>
    <h5>Timeline</h5>
    <ng-include src="'/templates/timeline/_timeline.html'"></ng-include>
  </div>
</mac-modal>`

I cannot get the "item" variable within "mac-modal-open" callback, no either in the mac-modal itself. How can I have access to the passed mac-modal-data? The docs don't show how.

**Comment by adrianlee44** [comment]
`mac-modal-open` only has access to the modal scope but not the icon. One way you can get the data is access `modal` service.

1. In the controller, inject `modal` service
2. You can access the opened modal by looking at `modal.opened` and the data will be stored on `modal.opened.options.data`.

You can find sample code in `docs.coffee`, https://github.com/angular-macgyver/MacGyver/blob/master/docs/doc.coffee#L9.

I hope I was able to answer your question. Let me know if you have any other questions.

**Comment by DavidValin** [comment]
@adrianlee44 Thanks you very much. I appreciate it. I was able to make it work now :+1:

**Comment by adrianlee44** [comment]
Happy to help!
