### ISSUE TITLE
Icon on menu items, autocomplete and tag-autocomplete

### ISSUE THREAD

**Issue by amandiobm** [angular-macgyver/MacGyver#21]
How to put an icon in the list items on autocomplete? It's possible?

**Comment by adrianlee44** [comment]
It is possible. Here's a [plunker](http://plnkr.co/edit/Sfft7kEPgs7CsXDJe1dH?p=preview) with icons in the dropdown

**Comment by adrianlee44** [comment]
Closing this for now. Reopen if more help is needed.
