### ISSUE TITLE
Can we use tag-autocomplete to select from existing tags and also accept new tags?

### ISSUE THREAD

**Issue by 2anandkr** [angular-macgyver/MacGyver#22]
I have a use case, wherein I want users to select tags from the menu if found in the database or add new ones. Is it possible? Can't make out from the docs.!
Can we use a separator to add new ones?

**Comment by adrianlee44** [comment]
I'm not sure if I fully understand your question but you can pass in an array of objects into `mac-autocomplete-source`. You can add new items to the array and should show up in the dropdown.

**Comment by adrianlee44** [comment]
Are you still having trouble with this? I'm closing this since there hasn't been activity for 10 days. Please reopen this if you need more help.
