### ISSUE TITLE
tag-autocomplete: How to do something when a tag is selected? 

### ISSUE THREAD

**Issue by 2anandkr** [angular-macgyver/MacGyver#23]
Can we listen on any event when a user selects a tag from the list?

**Comment by adrianlee44** [comment]
There is currently no event that gets emitted when user select a tag but a callback passed to `mac-autocomplete-on-select` will be invoked with the selected object.

**Comment by adrianlee44** [comment]
Are you still having trouble with this? Closing this for now. Please reopen if necessary.
