### ISSUE TITLE
Scrolling with keybord doesn't work on autocomplete

### ISSUE THREAD

**Issue by JorgeGomesRaimundo** [angular-macgyver/MacGyver#24]
If I use Autocomplete with a large source and use the keyboard down key to iterate through the options, the highlighted option eventually disappears because the menu list doesn't scroll down to keep up with the highlighted item.

To try, use the same example in http://angular-macgyver.github.io/MacGyver/0.6.1/#autocomplete but with a large source.
E.g.:
`mac-autocomplete-source="[\'Two\', \'households,\', \'both\', \'alike\', \'in\', \'dignity,\', \'In\', \'fair\', \'Verona,\', \'where\', \'we\', \'lay\', \'our\', \'scene,\', \'From\', \'ancient\', \'grudge\', \'break\', \'to\', \'new\', \'mutiny,\', \'Where\', \'civil\', \'blood\', \'makes\', \'civil\', \'hands\', \'unclean.\', \'From\', \'forth\', \'the\', \'fatal\', \'loins\', \'of\', \'these\', \'two\', \'foes\', \'A\', \'pair\', \'of\', \'star-cross\\\'d\', \'lovers\', \'take\', \'their\', \'life;\', \'Whose\', \'misadventured\', \'piteous\', \'overthrows\', \'Do\', \'with\', \'their\', \'death\', \'bury\', \'their\', \'parents\\\'\', \'strife.\']"`

Type 'a' on the input box and try to use the keyboard to see the bottom options.

Thanks.

**Comment by adrianlee44** [comment]
Let me take a look into this. Any chance you already have a plunker or jsbin with the code?

**Comment by JorgeGomesRaimundo** [comment]
Hello Adrian, sorry for the late reply, but I've been away.
We don't have any of those in our project.

**Comment by adrianlee44** [comment]
Hi @JorgeGomesRaimundo,
Having a large source doesn't seem to be a common use case and I think it makes the autocomplete component extremely hard to use. I would suggest limiting the number of entries populating the menu.

**Comment by adrianlee44** [comment]
Hasn't been active for 6 months. Closing this. Reopen if this is still an issue.
