### ISSUE TITLE
Groups itens

### ISSUE THREAD

**Issue by douglaslira** [angular-macgyver/MacGyver#25]
How to grouping items in the autocomplete? But click on the header separating the groups may not be clickable and how to insert an icon in front of the elements

Ex.:

USERS ----------
A
B
C
GROUPS -------
D
E
F

**Comment by adrianlee44** [comment]
Autocomplete does not support grouping items at the moment.

You can check out this [plunker](http://plnkr.co/edit/Sfft7kEPgs7CsXDJe1dH?p=preview) regarding to inserting an icon in front of each item.

**Comment by douglaslira** [comment]
i've created a new directive to render custom icons

http://plnkr.co/KtZEZJ81OXYh7UGWTUh4
