### ISSUE TITLE
Close Modal in controller

### ISSUE THREAD

**Issue by igormontella** [angular-macgyver/MacGyver#26]
I'm trying to show a modal when a error occur, I can open it using ng-show but, I'm unable to close when click on the close button, or pressing the key, or even clicking on the overview. May someone help?

**Comment by igormontella** [comment]
I'm trying to reach the Modal Service, but I don't know where to start.

**Comment by adrianlee44** [comment]
@igormontella, can you put some of the code in plunker or jsbin. That would help greatly.

You can inject modal service by injecting into your controller.

```javascript
myApp.controller('DemoController', ['$scope', 'modal', function($scope, modal) {
  $scope.hideModal = function () {
    modal.hide();
  }
}]);
```
