### ISSUE TITLE
Wrong offset calculation of scrollspy in ng-repeat

### ISSUE THREAD

**Issue by Mr-Wisey** [angular-macgyver/MacGyver#27]
I have a mac-scroll-spy-anchor on an ng-repeat Element. The problem is that the offset is probably calculated before the ng-repeat is fully rendered. Therefore the offset top is wrong the scrollspy navigation gets its classes to early. Thx for your help.

**Comment by adrianlee44** [comment]
You can emit `refresh-scroll-spy` after ng-repeat finishes and it will update the offset top accordingly.

**Comment by Mr-Wisey** [comment]
Perfect, thx.
