### ISSUE TITLE
angular#1.4.7 incompatible 

### ISSUE THREAD

**Issue by suoinguon** [angular-macgyver/MacGyver#28]
Do we have plan to make it compatible with angular 1.4+?

**Comment by adrianlee44** [comment]
I have been doing a bunch of rewrite on this project and the next version is definitely to make it compatible with AngularJS 1.4 and to look into making it compatible with 2.0

**Comment by suoinguon** [comment]
Hi @adrianlee44 , since I'm using bower and it says MacGyver not compatible with Angular 1.4 (I can still use it) . I just want to know when you will release next version ?

**Comment by adrianlee44** [comment]
I have a branch right now working on making it 1.4 compatible. Unfortunately I can't give you an accurate estimate of time at the moment.

**Comment by johnmanko** [comment]
We are in the process of migrating our app to Angular 2, and we use your package throughout our project. Do you have a estimate on v2 compatibility, otherwise we'll be forced to remove it. Thanks for this project!

**Comment by adrianlee44** [comment]
I would love to make MacGyver v2 compatible eventually. As V2 is in RC right now, I'll probably wait till the official version comes out before working on it.

I can't give you a roadmap or estimate at the current moment. Thanks for using this project.

**Comment by adrianlee44** [comment]
This is a pretty old issue and I'm going to close this for now. Please reopen this issue or open a new one.
