### ISSUE TITLE
Is there a way to scroll popovers in a scrollable div?

### ISSUE THREAD

**Issue by DirkAmmerlaan** [angular-macgyver/MacGyver#29]
Hi! Thanks for the great library! 

I have a question about the popovers. I am using them in a scrollable chat window (which isn't the body). When I scroll the chat div, the popovers don't scroll along (because they are appended to the body). Is there a way to append them to the pop-over a-tag or parent div? I've noticed that the tool-tips have a "mac-tooltip-inside" method. Is there something similar for the popovers? Or do I overlook something?

**Comment by adrianlee44** [comment]
Hi @DirkAmmerlaan,

Any chance you can provide an example on either jsbin, plunker or any other side you prefer?

**Comment by DirkAmmerlaan** [comment]
Hi @adrianlee44,

I've created a JSFiddle to show what I am trying to achieve: https://jsfiddle.net/e5hb5d9n/
(sorry for the extremely ugly implementation, but I hope it gives you an impression about what I am trying to do).

Thanks!

**Comment by adrianlee44** [comment]
Hi @DirkAmmerlaan,

Thanks for the JSFiddle. It's very helpful. Unfortunately, there is currently no option to change where the popover gets appended to. This is definitely a feature that can be added to popover in the next release.

I have opened another issue (#30) regarding to this enhancement. 

I would suggest hacking around this limitation by auto hiding the popover on scroll for now.

Thanks!

**Comment by DirkAmmerlaan** [comment]
@adrianlee44 Thanks for looking into the issue and your work-around suggestion.
I am looking forward to the next release!
