### ISSUE TITLE
MacTagAutocomplete: mac-tag-autocomplete-on-blur does not work

### ISSUE THREAD

**Issue by DirkAmmerlaan** [angular-macgyver/MacGyver#33]
Hi!

@adrianlee44 congrats with the new version release! 

I just updated MacGyer to the latest v1.0.0-rc.0 version and I ran into an issue. We lost a functionality in the macTagAutocomplete box. We've implemented the macTagAutocomplete to add multiple email addresses in one input box. On focus lost (blur) we autocomplete the last entry automatically:

```
<mac-tag-autocomplete 
mac-tag-autocomplete-disabled="true" 
mac-tag-autocomplete-selected="selectedUsers" 
mac-tag-autocomplete-model="selectedUserModel" 
mac-tag-autocomplete-label="display" 
mac-tag-autocomplete-events="blur" 
mac-tag-autocomplete-on-enter="addUser(item)" 
mac-tag-autocomplete-on-blur="addUserOnBlur(item)" 
mac-tag-autocomplete-placeholder="'Email address'"></mac-tag-autocomplete>
```
However this seems not to work any more. We use Angular 1.5.3. Should we implement it differently for the new version?

**Comment by adrianlee44** [comment]
Hi @DirkAmmerlaan.

I removed `mac-tag-autocomplete-events` and `mac-tag-autocomplete-on-*` attributes due to hacky implementation in the first place. I'll look into bring those attributes back in a different manner very soon.

Thanks

**Comment by DirkAmmerlaan** [comment]
@adrianlee44 thanks for your answer. For now we reverted the upgrade to the 0.6.1 version to still have the attributes. I am looking forward to see them back in future releases :)
