### ISSUE TITLE
macAutocomplete doesn't work in Bootstrap modal

### ISSUE THREAD

**Issue by mathewparet** [angular-macgyver/MacGyver#35]
I tried implementing macAutocomplete and it works everywhere in the page except when put inside a bootstrap modal. In the bootstrap modal the autocomplete field shows text box and if i key in anything, suggestions are also loaded (found out using a AngularJS debugger) but not shown on screen. If I use my keyboard arrow keys to select the data with an assumption that the the word I am looking for is the second one, then it is picking correct. Only thing is it isn't displaying the suggestions.

**Comment by adrianlee44** [comment]
Which version of MacGyver are you using? Also, any chance you can take a screenshot or put some sample code in either jsfiddle or jsbin?

**Comment by mathewparet** [comment]
I am using 1.0.0-rc.0. Unfortunately I can't provide a screenshot right now.

**Comment by fernandocastillo** [comment]
Just add z-index to class .mac-menu:


.mac-menu{
    z-index: 9999999;
}

**Comment by adrianlee44** [comment]
I hope setting the `z-index` works. I'm going to close this for now since there hasn't been any activities for the last few months.
