### ISSUE TITLE
mac-popover-refresh-on is not working for popover

### ISSUE THREAD

**Issue by aeisenberg** [angular-macgyver/MacGyver#38]
The documentation for `popover` mentions, `mac-popover-refresh-on` as a scope attribute, but that does not seem to work. Here is the template text I am using:

```
<mac-popover
  mac-popover-direction="below right"
  mac-popover-refresh-on="collapsable-table-header-changed"
  id="{{::directiveDetailsPopup.popoverId}}">
  <div class="directive--tooltip">
    <pre>{{directiveDetailsPopup.format()}}</pre>
  </div>
</mac-popover>
```

I would expect that whenever the `collapsable-table-header-changed` event is emitted on $rootScope, then the location and size of this popover will be recalculated. However, that is not happening. 

Looking at the code. I think the problem has to do with the declaration of `macPopoverDefaults` constant:
```
constant('macPopoverDefaults', {
  trigger: {
    offsetY: 0,
    offsetX: 0,
    trigger: 'click',
    container: null
  },
  element: {
    footer: false,
    header: false,
    title: '',
    direction: 'above left'
  },
  template: "<div class='mac-popover' ng-class='macPopoverClasses'>\
    <div class='tip'></div>\
    <div class='popover-header'>\
      <div class='title'>{{macPopoverTitle}}</div>\
    </div>\
    <div mac-popover-fill-content></div>\
  </div>"
}).
```
There needs to explicitly be added a `refreshOn` property (set to null or undefined). It should be an easy fix.

**Comment by adrianlee44** [comment]
Thanks for reporting this. Taking a look

**Comment by aeisenberg** [comment]
Thanks for the quick turnaround!
